### ISSUE TITLE
TypeError if set searchInKeys prop

### ISSUE THREAD

**Issue by reznik789** [Corjen/react-data-sort#5]
I got following error specifying  `searchInKeys` property

>TypeError: Cannot convert undefined or null to object

>DataSort.render
node_modules/react-data-sort/dist/index.esm.js:167
  164 | 
  165 | var pages = this.state.pages;
  166 | debugger;
167 | var keys = this.props.searchInKeys || data && data.length ? Object.keys(data[0]) : [];
  168 | 
  169 | // Search & sort data
  170 | var searched = searchQuery === '' ? data : matchSorter(data, searchQuery, { keys: keys });
View compiled

https://i.imgur.com/2Iv5SFB.png

https://i.imgur.com/IC1fJW2.png

**Comment by reznik789** [comment]
This error actual only for empty data array
You could see this here
https://codesandbox.io/s/j4lwjvk3n3

**Comment by reznik789** [comment]
Any updates?

**Comment by Corjen** [comment]
He @reznik789,

Sorry for the late response, have been busy.  The problem is manually setting the `searchInKeys` prop and passing it an empty array at the same time. If set the `searchInKeys` prop to `null`, it works.

There are two solutions to fixing this, the first being not rendering the Datasort component if the data array is empty, e.g.:

```js
function MyTable() {
  return !data.length ? null : <Datasort data={data} ...etc
}
``` 

The second is setting the searchInKey prop based on the length of the data array, e.g.:
```
<Datasort
    searchInKeys={!data.length ? null : ["email"]}
   ...etc
```

I agree though that error messages could be better in this regard. I'm planning to update react-data-sort with better error messages and typescript types, but need to find some time for it.

Hope this works for you!
